version: '3'
services:
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        depends_on:
            - registration-module
            - tracking-module
    registration-module:
        restart: always
        build:
            context: ./registration
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./registration:/app
        environment:
            - TO_EMAIL=youremail@mail.com
            - NODE_ENV1=production
    tracking-module:
        restart: always
        build:
            context: ./tracking_data_consumer
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./tracking_data_consumer:/app
        environment:
            - TO_EMAIL=youremail@mail.com
            - NODE_ENV1=production

#We can setup modules and databases to run along with docker-compose for dev purposes
#volumes:
#    redis_data:
#   mongo:
#  cassandra
